name: Build & deploy docs

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build-and-deploy:
    name: Build & deploy docs
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}

    steps:
      # Make the content of the repository accessible from a $GITHUB_WORKSPACE variable
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          pip install mkdocs

      - name: Build site
        run: mkdocs build --strict

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4